### ISSUE TITLE
Cant complete the build.

### ISSUE THREAD

**Issue by Shawzborne** [kevsmithpublic/MameAppleTV#1]
![screen shot 2015-11-09 at 11 07 26 am](https://cloud.githubusercontent.com/assets/5931778/11038660/1f8f0b42-86d2-11e5-99d8-11b6e75343bd.png)

what do I do to fix it?

**Comment by kevsmithpublic** [comment]
I can't see the error to help, scroll the left hand side down to show the error (in red) and paste that in and Ill have a look.

**Comment by johnstewart** [comment]
No the original poster, but I just grabbed this today and tried to compile with Xcode Version 7.0 (7A218)... EDIT: Belay that, it was Version 7.1 beta (7B75), duh. Downloading 7.1 beta 2 now to see if any different.

I get a similar error, one failure. When I click it it takes me to the General tab of the project where I can see under App Icons in red is the Source of "App Icon & Top Shelf". So I'm guessing this asset catalog is missing?

![_woleczn](https://cloud.githubusercontent.com/assets/1383441/11049807/9ccbe2ae-8706-11e5-8941-085e15575dc4.png)

Edit2: Finally scrolled to error:

(path)/MameAppleTV-master/res/roms/dkong.zip: No such file or directory

I created a roms directory in that path, and moved dkong.zip in there.... compliling!

Edit3: ack now it wants pacman.zip.

**Comment by kevsmithpublic** [comment]
Yes, The roms in the project are test roms which are excluded on check-in to github (via .gitingore), however they remain in the project. 

So to fix the compiler errors you need to
- Delete all the red .zip files under resources
- Drag your own roms into Resources

The project should now build

![screen shot 2015-11-10 at 12 15 34 pm](https://cloud.githubusercontent.com/assets/15688671/11054325/9bf102d4-87a5-11e5-8de9-30412cb16bd6.png)

**Comment by johnstewart** [comment]
Thanks, kevsmithpublic; appreciate the response!

I wanted to report I am still seeing a problem after your suggested fix.

Step by step to reproduce:
- Download and extracted MameAppleTV-master.zip
- Open iMAME4tvOS.xcodeproj with Xcode Version 7.2 beta (7C46t)
- In Xcode left panel, delete above red ROMs from Resources folder.
- Copy over some ROMs to Resources (in my case, 1942.zip, 1943.zip, dkong.zip, jumpbug.zip, and pacman.zip)... although this step looks irrelevant to the error below.
- Build (with Apple TV 1080p as target)

I get this error:

```
Ld /Users/jstewart/Library/Developer/Xcode/DerivedData/iMAME4tvOS-hhakznhafuuxcfazsiszggdjmqfy/Build/Products/Debug-appletvsimulator/tvOS\ Mame.app/tvOS\ Mame normal x86_64
    cd "/Users/jstewart/Dropbox/John Development/Downloaded/MameAppleTV-master"
    export PATH="/Applications/Xcode-beta.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export TVOS_DEPLOYMENT_TARGET=9.0
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator9.1.sdk -L/Users/jstewart/Library/Developer/Xcode/DerivedData/iMAME4tvOS-hhakznhafuuxcfazsiszggdjmqfy/Build/Products/Debug-appletvsimulator -L/Users/jstewart/Dropbox/John\ Development/Downloaded/MameAppleTV-master/lib -F/Users/jstewart/Library/Developer/Xcode/DerivedData/iMAME4tvOS-hhakznhafuuxcfazsiszggdjmqfy/Build/Products/Debug-appletvsimulator -filelist /Users/jstewart/Library/Developer/Xcode/DerivedData/iMAME4tvOS-hhakznhafuuxcfazsiszggdjmqfy/Build/Intermediates/iMAME4tvOS.build/Debug-appletvsimulator/iMame4tvOS.build/Objects-normal/x86_64/tvOS\ Mame.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mtvos-simulator-version-min=9.0 -Xlinker -objc_abi_version -Xlinker 2 -L/Applications/Xcode-beta.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator9.1.sdk/usr/lib -lm -lpthread -lm -lc -lz -Llib -Wall -Wno-sign-compare -Wunused -Wpointer-arith -Wcast-align -Waggregate-return -Wshadow -lobjc -lpthread -fobjc-link-runtime -L/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/appletvsimulator -Xlinker -add_ast_path -Xlinker /Users/jstewart/Library/Developer/Xcode/DerivedData/iMAME4tvOS-hhakznhafuuxcfazsiszggdjmqfy/Build/Intermediates/iMAME4tvOS.build/Debug-appletvsimulator/iMame4tvOS.build/Objects-normal/x86_64/tvOS_Mame.swiftmodule -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/jstewart/Library/Developer/Xcode/DerivedData/iMAME4tvOS-hhakznhafuuxcfazsiszggdjmqfy/Build/Intermediates/iMAME4tvOS.build/Debug-appletvsimulator/iMame4tvOS.build/tvOS\ Mame.app.xcent -framework Foundation -framework AudioToolbox -framework GameController -Xlinker -dependency_info -Xlinker /Users/jstewart/Library/Developer/Xcode/DerivedData/iMAME4tvOS-hhakznhafuuxcfazsiszggdjmqfy/Build/Intermediates/iMAME4tvOS.build/Debug-appletvsimulator/iMame4tvOS.build/Objects-normal/x86_64/tvOS\ Mame_dependency_info.dat -o /Users/jstewart/Library/Developer/Xcode/DerivedData/iMAME4tvOS-hhakznhafuuxcfazsiszggdjmqfy/Build/Products/Debug-appletvsimulator/tvOS\ Mame.app/tvOS\ Mame

Undefined symbols for architecture x86_64:
  "cpu_setOPbase26lew(int)", referenced from:
      arm_dasm(char*, unsigned int) in arm.o
      fill_queue() in arm.o
  "_bt_send_l2cap", referenced from:
      _wiimote_send in wiimote.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

If it's easier to see, a screenshot:

![rouw9_1j](https://cloud.githubusercontent.com/assets/1383441/11070594/1851d0a0-87a2-11e5-8bb8-6e002cc5899f.png)

**Comment by kevsmithpublic** [comment]
You need to plug in your Apple TV and select that as the target (or select "Generic tvOS Device" then it should build successfully.

The error "Undefined symbols for architecture x86_64" means it's trying to create a simulator build which isn't possible currently.

**Comment by johnstewart** [comment]
Indeed you are correct. Thank you, sir!

**Comment by theDVUSone** [comment]
Is there any way to increase the Mame version to 0.164?

**Comment by kevsmithpublic** [comment]
No without major work, closing this issue.

**Comment by montrothstein** [comment]
For anyone coming across this, to change the target from the simulator to your plugged in AppleTV device click on "iMame4tvOS" in the toolbar (right of the square stop icon) then the pop-up menu should show your device.

**Comment by dawidth** [comment]
Thanks for your work, this is my problem. 

![capturadepantallamame](https://cloud.githubusercontent.com/assets/17429103/13284542/32a426f0-daf5-11e5-97a1-a061482e9efa.png)

**Comment by davemchine** [comment]
Mine looks exactly like dawidth's after I deleted the zip files mentioned above.
