### ISSUE TITLE
N64 rom support

### ISSUE THREAD

**Issue by hilljon86** [kevsmithpublic/MameAppleTV#3]
Does this emulator support n64 roms?  I deployed to my apple tv tonight with the .n64 roms files in the resources folder but when the app starts on the apple tv it says "no available games found".

**Comment by appletv4** [comment]
This app is only for old arcade games

**Comment by kevsmithpublic** [comment]
The code will only load Mame roms, specifically the version Mame 37b5 set. Anything else will not work or fail to load.

Closing issue.
